[package]
name = "notification_app_api"
version = "0.2.0"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notification_app_lib = {path = "../notification_app_lib"}
notification_app_bot = {path = "../notification_app_bot"}
actix-web = "3.3"
actix-web-httpauth = "0.5"
actix-rt = "1.1"
deadqueue = "0.2"
anyhow = "1.0"
thiserror = "1.0"
lazy_static = "1.4"
stack-string = { git = "https://github.com/ddboline/stack-string-rs.git", tag="0.2.0" }
