[package]
name = "notification_app_lib"
version = "0.3.6"
authors = ["Daniel Boline <ddboline@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15"
anyhow = "1.0"
envy = "0.4"
dirs = "4.0"
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
url = "2.2"
derive_more = "0.99"
time = {version="0.3", features=["serde-human-readable", "macros", "formatting"]}
sts_profile_auth = "0.7"
toml = "0.5"
tokio = {version="1.21", features=["full"]}
rusoto_core = {version = "0.48", default_features = false, features=["rustls"]}
rusoto_ses = {version = "0.48", default_features = false, features=["rustls"]}
stack-string = "0.7"

[dev-dependencies]
tempfile = "3.3"
