openapi: '3.1.0'
info:
  title: Notification API
  description: Simple Notification Service
  contact:
    name: Daniel Boline
    email: ddboline@gmail.com
  license:
    name: ''
  version: '0.5.1'
paths:
  /notify:
    post:
      operationId: notify_telegram
      parameters:
      - name: authorization
        in: header
        description: Bearer Authorization
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TelegramMessage'
        required: true
      responses:
        '201':
          description: Send Notification
          content:
            text/html:
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  message:
                    type: string
        '401':
          description: Not Authorized
          content:
            text/html:
              schema:
                type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                required:
                - message
                properties:
                  message:
                    type: string
components:
  schemas:
    TelegramMessage:
      type: object
      required:
      - recipient
      - message
      properties:
        message:
          type: string
        recipient:
          type: string
