name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install deps
      run: |
        rustup update

    - name: Clippy
      run: cargo clippy -- -W clippy::pedantic

    - name: Build
      run: cargo build --workspace

    - name: Run tests
      run: |
        cargo test --workspace && \
        cargo install cargo-tarpaulin --version 0.18.0-alpha3 && \
        cargo tarpaulin --verbose --all-features --workspace --out Xml --avoid-cfg-tarpaulin
      env:
        API_TOKENS_PATH: /tmp/config.env

    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}

    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: cobertura.xml
